import sys
sys.path.append('..')

from sift.constants import email_providers

DISPOSABLE_EMAIL_PROVIDERS = email_providers.DISPOSABLE_EMAIL_PROVIDERS

def is_disposable(domain: str) -> bool:
    '''
        @param {domain: str} - a domain address
        @return {bool}

        Verfies whether given email is disposable
        i.e., email generated by some temp mail generators
    '''
    if domain in DISPOSABLE_EMAIL_PROVIDERS:
        return True

    return False
